### Comments following parameters are not supported; they must be on a separate line.
### No extra spaces are allowed between options and values.
## https://mpv.io/manual/master/#options-ytdl

ytdl_path=/opt/homebrew/bin/yt-dlp
all_formats=no
force_all_formats=no
use_manifests=yes